#include <stdio.h>
#include <stdint.h>
#include <string.h>

// --- Instruction Opcodes (Package 1) ---
#define OP_ADD  0
#define OP_SUB  1
#define OP_MULI 2
#define OP_ADDI 3
#define OP_BNE  4
#define OP_ANDI 5
#define OP_XORI 6
#define OP_J    7
#define OP_SLL  8
#define OP_SRL  9
#define OP_LW   10
#define OP_SW   11

// ==========================================
// 1. GLOBAL HARDWARE STATE
// ==========================================
int clock_cycle = 1;
int32_t memory[2048];    // 0-1023: Instructions, 1024-2047: Data
int32_t registers[32];   // R0 to R31 (R0 is always 0)
int32_t PC = 0;          // Program Counter

// ==========================================
// 2. THE PIPELINE BATON (Instruction Context)
// ==========================================
typedef struct {
    int is_active;           // 1 if instruction is here, 0 if empty
    int cycles_remaining;    // Tracks the 2-cycle requirement for ID and EX

    // Data populated during FETCH
    int32_t instruction_address; // Where did this instruction come from in memory?
    int32_t raw_instruction;     // The raw 32-bit binary pulled from memory

    // Data populated during DECODE
    // We parse all fields just in case, even if the specific instruction type doesn't use them
    int opcode;
    int r1, r2, r3, shamt;
    int32_t imm, address;
    int32_t val_r2; // Value read from r2 register during Decode
    int32_t val_r3; // Value read from r3 register during Decode

    // Destination Register (Where is the result going?)
    int dest_reg;            // Register to write back to (0 to 31)

    // Data populated during EXECUTE
    int32_t alu_result;      // Result of math/logic operations
    int branch_taken;        // 1 if a branch/jump condition was met, 0 otherwise
    int32_t branch_target;   // The calculated address to jump to (if branch_taken == 1)

    // Data populated during MEMORY
    int32_t mem_read_data;   // Data loaded from main memory (for LW)

    // Control Signals (Generated by Decode)
    int reg_write;           // 1 if WB should write to dest_reg
    int mem_read;            // 1 if MEM should read from memory
    int mem_write;           // 1 if MEM should write to memory
    int mem_to_reg;          // 1 if WB should write Memory Data, 0 for ALU Result

} InstructionContext;

// Pipeline Stage Registers (What is currently sitting in the stage)
InstructionContext IF_Stage  = {0};
InstructionContext ID_Stage  = {0};
InstructionContext EX_Stage  = {0};
InstructionContext MEM_Stage = {0};
InstructionContext WB_Stage  = {0};

// ==========================================
// 3. STAGE FUNCTION PROTOTYPES (For the rest of the team)
// ==========================================
void Fetch();
void Decode();
void Execute();
void MemoryAccess();
void WriteBack();
void PrintCycleState();

// ==========================================
// 4. THE MAIN CLOCK ENGINE
// ==========================================
int main() {
    // Role 2 (Parser) will inject their function here to load program.txt into memory[]
    // InitializeParser(); 
    
    // Hardcode a dummy instruction to test the fetch cycle (ADDI R1, R0, 5)
    memory[0] = 0b00110000100000000000000000000101; 
    
    // The processor runs until all pipeline stages are empty AND we are out of instructions
    while (1) {
        // Stop condition: If PC is out of instruction memory bounds and pipeline is empty
        if (PC >= 1024 && !IF_Stage.is_active && !ID_Stage.is_active && 
            !EX_Stage.is_active && !MEM_Stage.is_active && !WB_Stage.is_active) {
            break; 
        }

        // ----------------------------------------------------
        // PROCESS STAGES (Reverse order to prevent overwriting)
        // ----------------------------------------------------
        
        // 1. WRITE BACK (Takes 1 cycle, runs on Odd cycles usually)
        if (WB_Stage.is_active) {
            
            // HAZARD HANDLING: Delayed flush matching the TA's X+3 timeline.
            // The branch_taken flag rides the baton through EX -> MEM -> WB.
            // By the time it reaches WB, the "wrong" instructions have naturally
            // populated EX and ID, exactly as the document's trace shows.
            if (WB_Stage.branch_taken) {
                PC = WB_Stage.branch_target; // Update PC for the new fetch below
                memset(&EX_Stage, 0, sizeof(InstructionContext)); // Drop instruction in EX
                memset(&ID_Stage, 0, sizeof(InstructionContext)); // Drop instruction in ID
            }
            
            WriteBack();
            // Instruction is finished, clear it out.
            memset(&WB_Stage, 0, sizeof(InstructionContext)); 
        }

        // 2. MEMORY (Takes 1 cycle, runs on Even cycles)
        if (MEM_Stage.is_active) {
            MemoryAccess();
            WB_Stage = MEM_Stage; // Direct transfer to WB
            memset(&MEM_Stage, 0, sizeof(InstructionContext));
        }

        // 3. EXECUTE (Takes 2 cycles)
        if (EX_Stage.is_active) {
            EX_Stage.cycles_remaining++;
            
            // Execute() is called twice, ensure no duplicate state changes inside it!
            Execute();
            
            // Only pass to MEM if it has finished its 2nd cycle
            if (EX_Stage.cycles_remaining == 2) {
                MEM_Stage = EX_Stage; // Direct transfer to MEM (branch data rides along!)
                MEM_Stage.cycles_remaining = 0; // Reset for MEM stage
                memset(&EX_Stage, 0, sizeof(InstructionContext));
            }
        }

        // 4. DECODE (Takes 2 cycles)
        if (ID_Stage.is_active) {
            ID_Stage.cycles_remaining++;
            
            // Decode() is called twice, ensure no duplicate state changes inside it!
            Decode();
            
            // Only pass to EX if it has finished its 2nd cycle
            if (ID_Stage.cycles_remaining == 2) {
                EX_Stage = ID_Stage; // Direct transfer to EX
                EX_Stage.cycles_remaining = 0; // Reset for EX stage
                memset(&ID_Stage, 0, sizeof(InstructionContext));
            }
        }

        // 5. FETCH (Runs only on ODD clock cycles)
        if (clock_cycle % 2 != 0 && PC >= 0 && PC < 1024) {
            IF_Stage.is_active = 1;
            Fetch();
            ID_Stage = IF_Stage; // Direct transfer to ID
            memset(&IF_Stage, 0, sizeof(InstructionContext));
        }

        // Enforce Hardwired Zero Register
        registers[0] = 0;

        // Print outputs for grading
        PrintCycleState();

        clock_cycle++;
        
        // Safety break for testing to prevent infinite loop
        if(clock_cycle > 25) break; 
    }

    printf("\n--- Simulation Complete in %d Cycles ---\n", clock_cycle - 1);
    return 0;
}

// ==========================================
// DUMMY FUNCTIONS (For testing the loop)
// ==========================================
void Fetch() {
    if (memory[PC] == 0) { // Safety check to stop if memory is empty
        PC = 1024; // Trigger end condition
        IF_Stage.is_active = 0; // Don't pass an empty instruction down
        return;
    }
    IF_Stage.instruction_address = PC;
    IF_Stage.raw_instruction = memory[PC];
    printf("  [IF] Fetched instruction 0x%08X at PC %d\n", IF_Stage.raw_instruction, PC);
    PC++; // Increment PC
}

void Decode() { 
    if (ID_Stage.cycles_remaining == 1) {
        int32_t inst = ID_Stage.raw_instruction;
        
        // Parse all fields regardless of instruction format
        ID_Stage.opcode = (inst >> 28) & 0xF;
        ID_Stage.r1     = (inst >> 23) & 0x1F;
        ID_Stage.r2     = (inst >> 18) & 0x1F;
        ID_Stage.r3     = (inst >> 13) & 0x1F;
        ID_Stage.shamt  = (inst >> 8)  & 0x1F;
        
        // Immediate (18 bits, sign extended)
        int32_t imm = inst & 0x3FFFF;
        if (imm & 0x20000) {
            imm |= 0xFFFC0000;
        }
        ID_Stage.imm = imm;
        
        // Address (28 bits)
        ID_Stage.address = inst & 0xFFFFFFF;
        
        // Read from registers (only val_r2 and val_r3 per naming convention)
        ID_Stage.val_r2 = registers[ID_Stage.r2];
        ID_Stage.val_r3 = registers[ID_Stage.r3];
        
        // Default control signals
        ID_Stage.reg_write  = 0;
        ID_Stage.mem_read   = 0;
        ID_Stage.mem_write  = 0;
        ID_Stage.mem_to_reg = 0;
        ID_Stage.dest_reg   = -1;
        
        switch (ID_Stage.opcode) {
            case 0: // ADD
            case 1: // SUB
            case 8: // SLL
            case 9: // SRL
            case 2: // MULI
            case 3: // ADDI
            case 5: // ANDI
            case 6: // XORI
                ID_Stage.reg_write = 1;
                ID_Stage.dest_reg = ID_Stage.r1;
                break;
                
            case 10: // LW
                ID_Stage.reg_write = 1;
                ID_Stage.mem_read = 1;
                ID_Stage.mem_to_reg = 1;
                ID_Stage.dest_reg = ID_Stage.r1;
                break;
                
            case 11: // SW
                ID_Stage.mem_write = 1;
                break;
                
            case 4: // BNE
            case 7: // J
                // No WB, no MEM read/write
                break;
        }
        
        printf("  [ID] Cycle 1: Decoded Instruction at PC %d: Opcode=%d, R1=%d, R2=%d, R3=%d, Imm=%d\n", 
               ID_Stage.instruction_address, ID_Stage.opcode, ID_Stage.r1, ID_Stage.r2, ID_Stage.r3, ID_Stage.imm);
    } else if (ID_Stage.cycles_remaining == 2) {
        printf("  [ID] Cycle 2: Decode complete for instruction at PC %d.\n", ID_Stage.instruction_address);
    }
}

void Execute() { 
    /* 
     * ALU Engineer (EX - Part 1): Handles all math/logic/shift instructions.
     * This function is called TWICE per instruction (2-cycle Execute stage).
     *
     * Cycle 1 (cycles_remaining == 1): Perform the actual ALU computation.
     * Cycle 2 (cycles_remaining == 2): Result already computed; just log completion.
     *
     * Non-ALU opcodes (BNE, J) are left for the Branch & Hazard Manager (Part 2).
     * LW/SW address calculation (R2 + IMM) is also done here since it's ALU work.
     */

    // --- CYCLE 1: Perform the computation ---
    if (EX_Stage.cycles_remaining == 1) {

        int32_t val_r2 = EX_Stage.val_r2;  // Value of source register R2
        int32_t val_r3 = EX_Stage.val_r3;  // Value of source register R3 (R-Type only)
        int32_t imm    = EX_Stage.imm;     // Sign-extended immediate (I-Type only)
        int shamt      = EX_Stage.shamt;   // Shift amount (SLL/SRL only)

        switch (EX_Stage.opcode) {

            case OP_ADD:
                // ADD R1, R2, R3  ->  R1 = R2 + R3
                EX_Stage.alu_result = val_r2 + val_r3;
                printf("  [EX] ADD: R%d = %d + %d = %d\n",
                       EX_Stage.r1, val_r2, val_r3, EX_Stage.alu_result);
                break;

            case OP_SUB:
                // SUB R1, R2, R3  ->  R1 = R2 - R3
                EX_Stage.alu_result = val_r2 - val_r3;
                printf("  [EX] SUB: R%d = %d - %d = %d\n",
                       EX_Stage.r1, val_r2, val_r3, EX_Stage.alu_result);
                break;

            case OP_MULI:
                // MULI R1, R2, IMM  ->  R1 = R2 * IMM
                EX_Stage.alu_result = val_r2 * imm;
                printf("  [EX] MULI: R%d = %d * %d = %d\n",
                       EX_Stage.r1, val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_ADDI:
                // ADDI R1, R2, IMM  ->  R1 = R2 + IMM
                EX_Stage.alu_result = val_r2 + imm;
                printf("  [EX] ADDI: R%d = %d + %d = %d\n",
                       EX_Stage.r1, val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_ANDI:
                // ANDI R1, R2, IMM  ->  R1 = R2 & IMM
                EX_Stage.alu_result = val_r2 & imm;
                printf("  [EX] ANDI: R%d = %d & %d = %d\n",
                       EX_Stage.r1, val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_XORI:
                // XORI R1, R2, IMM  ->  R1 = R2 ^ IMM
                EX_Stage.alu_result = val_r2 ^ imm;
                printf("  [EX] XORI: R%d = %d ^ %d = %d\n",
                       EX_Stage.r1, val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_SLL:
                // SLL R1, R2, SHAMT  ->  R1 = R2 << SHAMT
                // R3 is 0 in the instruction format for shift instructions.
                // SHAMT is always positive (5-bit unsigned).
                EX_Stage.alu_result = val_r2 << shamt;
                printf("  [EX] SLL: R%d = %d << %d = %d\n",
                       EX_Stage.r1, val_r2, shamt, EX_Stage.alu_result);
                break;

            case OP_SRL:
                // SRL R1, R2, SHAMT  ->  R1 = R2 >> SHAMT (logical, zero-fill)
                // Cast to uint32_t to ensure logical shift (no sign extension).
                // SHAMT is always positive (5-bit unsigned).
                EX_Stage.alu_result = (int32_t)((uint32_t)val_r2 >> shamt);
                printf("  [EX] SRL: R%d = %d >>> %d = %d\n",
                       EX_Stage.r1, val_r2, shamt, EX_Stage.alu_result);
                break;

            case OP_LW:
                // LW R1, R2, IMM  ->  Address = R2 + IMM (ALU computes the address)
                EX_Stage.alu_result = val_r2 + imm;
                printf("  [EX] LW: Address = %d + %d = %d\n",
                       val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_SW:
                // SW R1, R2, IMM  ->  Address = R2 + IMM (ALU computes the address)
                EX_Stage.alu_result = val_r2 + imm;
                printf("  [EX] SW: Address = %d + %d = %d\n",
                       val_r2, imm, EX_Stage.alu_result);
                break;

            case OP_BNE:
            case OP_J:
                // Branch & Jump are handled by Part 2 (Branch & Hazard Manager)
                break;

            default:
                printf("  [EX] WARNING: Unknown opcode %d\n", EX_Stage.opcode);
                break;
        }

        printf("  [EX] Cycle 1 of 2 for instruction at PC %d (opcode %d)\n",
               EX_Stage.instruction_address, EX_Stage.opcode);

    // --- CYCLE 2: Computation already done, just log ---
    } else if (EX_Stage.cycles_remaining == 2) {
        printf("  [EX] Cycle 2 of 2 for instruction at PC %d (opcode %d). ALU Result = %d\n",
               EX_Stage.instruction_address, EX_Stage.opcode, EX_Stage.alu_result);
    }
}

void MemoryAccess() { 
    /* Role 6 builds this */ 
}

void WriteBack() { 
    /* Role 6 builds this */ 
}

void PrintCycleState() {
    printf("Cycle %d:\tID_Active: %d \tEX_Active: %d\n", clock_cycle, ID_Stage.is_active, EX_Stage.is_active);
}