#include <stdio.h>
#include <stdint.h>
#include <string.h>

// ==========================================
// 1. GLOBAL HARDWARE STATE
// ==========================================
int clock_cycle = 1;
int32_t memory[2048];    // 0-1023: Instructions, 1024-2047: Data
int32_t registers[32];   // R0 to R31 (R0 is always 0)
int32_t PC = 0;          // Program Counter
int skip_next_fetch = 0; // <--- NEW: Hardware delay simulator for branching

// ==========================================
// 2. THE PIPELINE BATON (Instruction Context)
// ==========================================
typedef struct {
    int is_active;           // 1 if instruction is here, 0 if empty
    int cycles_in_stage;     // Tracks the 2-cycle requirement for ID and EX
    
    // Fetch Data
    int32_t pc_address;      
    int32_t raw_instruction; 

    // Decode Data
    int opcode;
    int r1, r2, r3, shamt;
    int32_t imm, address;
    int32_t val_r1, val_r2, val_r3; 

    // NEW: Destination Register (Where is the result going?)
    int dest_reg;            // Register to write back to (0 to 31)

    // Execute Data
    int32_t alu_result;
    int branch_taken;        // 1 if branch/jump is taken
    int32_t branch_target;   // Where to jump to

    // Memory Data
    int32_t mem_read_data;

    // NEW: Control Signals (Generated by Decode)
    int reg_write;           // 1 if WB should write to dest_reg
    int mem_read;            // 1 if MEM should read from memory
    int mem_write;           // 1 if MEM should write to memory
    int mem_to_reg;          // 1 if WB should write Memory Data, 0 for ALU Result

} InstructionContext;

// Pipeline Stage Registers (What is currently sitting in the stage)
InstructionContext IF_Stage  = {0};
InstructionContext ID_Stage  = {0};
InstructionContext EX_Stage  = {0};
InstructionContext MEM_Stage = {0};
InstructionContext WB_Stage  = {0};

// ==========================================
// 3. STAGE FUNCTION PROTOTYPES (For the rest of the team)
// ==========================================
void Fetch();
void Decode();
void Execute();
void MemoryAccess();
void WriteBack();
void PrintCycleState();

// ==========================================
// 4. THE MAIN CLOCK ENGINE
// ==========================================
int main() {
    // Role 2 (Parser) will inject their function here to load program.txt into memory[]
    // InitializeParser(); 
    
    // Hardcode a dummy instruction to test the fetch cycle (ADDI R1, R0, 5)
    memory[0] = 0b00110000100000000000000000000101; 
    
    // The processor runs until all pipeline stages are empty AND we are out of instructions
    while (1) {
        // Stop condition: If PC is out of instruction memory bounds and pipeline is empty
        if (PC >= 1024 && !IF_Stage.is_active && !ID_Stage.is_active && 
            !EX_Stage.is_active && !MEM_Stage.is_active && !WB_Stage.is_active) {
            break; 
        }

        // ----------------------------------------------------
        // PROCESS STAGES (Reverse order to prevent overwriting)
        // ----------------------------------------------------
        
        // 1. WRITE BACK (Takes 1 cycle, runs on Odd cycles usually)
        if (WB_Stage.is_active) {
            WriteBack();
            // Instruction is finished, clear it out.
            memset(&WB_Stage, 0, sizeof(InstructionContext)); 
        }

        // 2. MEMORY (Takes 1 cycle, runs on Even cycles)
        if (MEM_Stage.is_active) {
            MemoryAccess();
            WB_Stage = MEM_Stage; // Direct transfer to WB
            memset(&MEM_Stage, 0, sizeof(InstructionContext));
        }

        // 3. EXECUTE (Takes 2 cycles)
        if (EX_Stage.is_active) {
            EX_Stage.cycles_in_stage++;
            
            // Execute() is called twice, ensure no duplicate state changes inside it!
            Execute();
            
            // Only pass to MEM if it has finished its 2nd cycle
            if (EX_Stage.cycles_in_stage == 2) {
                
                // HAZARD HANDLING: If a branch is taken, flush the pipeline
                if (EX_Stage.branch_taken) {
                    PC = EX_Stage.branch_target; // Update PC
                    memset(&ID_Stage, 0, sizeof(InstructionContext)); // Flush Decode directly
                    skip_next_fetch = 1; // <--- NEW: Skip the next fetch cycle
                }
                
                MEM_Stage = EX_Stage; // Direct transfer to MEM
                MEM_Stage.cycles_in_stage = 0; // Reset for MEM stage
                memset(&EX_Stage, 0, sizeof(InstructionContext));
            }
        }

        // 4. DECODE (Takes 2 cycles)
        if (ID_Stage.is_active) {
            ID_Stage.cycles_in_stage++;
            
            // Decode() is called twice, ensure no duplicate state changes inside it!
            Decode();
            
            // Only pass to EX if it has finished its 2nd cycle
            if (ID_Stage.cycles_in_stage == 2) {
                EX_Stage = ID_Stage; // Direct transfer to EX
                EX_Stage.cycles_in_stage = 0; // Reset for EX stage
                memset(&ID_Stage, 0, sizeof(InstructionContext));
            }
        }

        // 5. FETCH (Runs only on ODD clock cycles and when MEM is not active)
        if (clock_cycle % 2 != 0 && !MEM_Stage.is_active && PC >= 0 && PC < 1024) {
            if (skip_next_fetch) {         // <--- NEW: Check if we need to simulate the delay
                skip_next_fetch = 0;       // <--- NEW: Reset the flag, and do NOT fetch this cycle
            } else {                       // <--- NEW: Otherwise, fetch normally
                IF_Stage.is_active = 1;
                Fetch();
                ID_Stage = IF_Stage; // Direct transfer to ID
                memset(&IF_Stage, 0, sizeof(InstructionContext));
            }                              // <--- NEW
        }

        // Enforce Hardwired Zero Register
        registers[0] = 0;

        // Print outputs for grading
        PrintCycleState();

        clock_cycle++;
        
        // Safety break for testing to prevent infinite loop
        if(clock_cycle > 25) break; 
    }

    printf("\n--- Simulation Complete in %d Cycles ---\n", clock_cycle - 1);
    return 0;
}

// ==========================================
// DUMMY FUNCTIONS (For testing the loop)
// ==========================================
void Fetch() {
    if (memory[PC] == 0) { // Safety check to stop if memory is empty
        PC = 1024; // Trigger end condition
        IF_Stage.is_active = 0; // Don't pass an empty instruction down
        return;
    }
    IF_Stage.pc_address = PC;
    IF_Stage.raw_instruction = memory[PC];
    PC++; // Increment PC
}

void Decode() { 
    /* Role 3 builds this. Remember it might be called twice per instruction! */ 
    // Set dest_reg and control signals here too!
}

void Execute() { 
    /* Roles 4 & 5 build this. Remember it might be called twice per instruction! */ 
}

void MemoryAccess() { 
    /* Role 6 builds this */ 
}

void WriteBack() { 
    /* Role 6 builds this */ 
}

void PrintCycleState() {
    printf("Cycle %d:\tID_Active: %d \tEX_Active: %d\n", clock_cycle, ID_Stage.is_active, EX_Stage.is_active);
}